# Generated by Django 4.0.3 on 2022-07-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='hateCategory',
        ),
        migrations.RemoveField(
            model_name='message',
            name='isHatefulInModelView',
        ),
        migrations.RemoveField(
            model_name='message',
            name='isHatefulInUserView',
        ),
    ]
