# Generated by Django 4.0.4 on 2022-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_message_remove_question_owner_remove_question_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isOffensive',
            field=models.BooleanField(null=True),
        ),
    ]
