# Generated by Django 4.0.4 on 2022-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_message_isoffensive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='isOffensive',
            new_name='isOffensiveInModelView',
        ),
        migrations.AddField(
            model_name='message',
            name='isOffensiveInUserView',
            field=models.BooleanField(null=True),
        ),
    ]
