# Generated by Django 4.0.4 on 2022-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_rename_isoffensive_message_isoffensiveinmodelview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.AddField(
            model_name='message',
            name='userIP',
            field=models.CharField(default='1', max_length=16),
        ),
    ]
