# Generated by Django 4.0.3 on 2022-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
